In [4]:
import numpy as np        # import numpy



In [5]:
# 1 dimensional array
list1=[1,2,3,4,3]
arr1=np.array(list1)
arr1
print(arr1.ndim)   #dimensional


1


In [ ]:
print(list1*2)
print(arr1*2)
type(arr1) #dtype
arr1.dtype   # datatype


[1, 2, 3, 4, 3, 1, 2, 3, 4, 3]
[2 4 6 8 6]


numpy.ndarray

In [ ]:
arr2=np.array([1,2,3,4])    #another form
print(arr2)
arr2.size            #to find the array  size
arr2.shape           #find the shape(how many columns and rows)
arr2.dtype            #datatype

[1 2 3 4]


dtype('int64')

In [ ]:
# 2 dimensional array
arr21=np.array([
    [1,2,3],
    [4,3,2],
    [1,4,9],
])
print(arr21)
type(arr21)         #to find the array type(dtype)
arr21.size        #to find the array  size
arr21.ndim        #to find the dimensional
arr21.shape       ##find the shape(how many columns and rows)
arr21.dtype       #datatype



[[1 2 3]
 [4 3 2]
 [1 4 9]]


dtype('int64')

In [12]:
# 3 dimensional array
arr3=np.array([
    [[2,3,4],[3,4,1],[6,7,8]],
    [[1,7,8],[3,5,6],[9,7,6]],
    [[1,7,8],[3,5,6],[9,7,6]],
    [[1,7,8],[3,5,6],[9,7,6]]
])
print(arr3)
arr3.size    #to find the array  size
type(arr3)    #to find the array type(dtype)
arr3.ndim    #to find the dimensional
arr3.shape   #find the shape(how many columns and rows)

[[[2 3 4]
  [3 4 1]
  [6 7 8]]

 [[1 7 8]
  [3 5 6]
  [9 7 6]]

 [[1 7 8]
  [3 5 6]
  [9 7 6]]

 [[1 7 8]
  [3 5 6]
  [9 7 6]]]


(4, 3, 3)

TypeError: reshape() missing 1 required positional argument: 'shape'

In [16]:
# 2 dimensional array
arr21=np.array([
    [1,2,3],
    [4,3,2],
    [1,4,9],
])
arr21.dtype
arr212=arr21.astype(np.float16)
arr212


array([[1., 2., 3.],
       [4., 3., 2.],
       [1., 4., 9.]], dtype=float16)

In [19]:
arr31=np.zeros((2,3))
arr31

array([[0., 0., 0.],
       [0., 0., 0.]])

In [20]:
arr32=np.ones((2,3,2))
arr32


array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [ ]:
arr34=np.arange(100)
arr34
arr34=np.arange((10,100))
arr34=np.arange((10,100,10))   #start,stop,increment

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [ ]:
arr25=np.linspace(1,50,9)      #spacing     start stop incre
arr25

array([ 1.   ,  7.125, 13.25 , 19.375, 25.5  , 31.625, 37.75 , 43.875,
       50.   ])

In [ ]:
arr54=np.eye(5)    #diagonal valuess are 1 and 0
arr54

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
arr454=np.full(5,5)   #fill with any value specified
arr454

array([5, 5, 5, 5, 5])

In [30]:
arr67=np.random(4,3)
arr67

TypeError: 'module' object is not callable

In [ ]:
import numpy as np 

IndexError: index 1 is out of bounds for axis 3 with size 1